### ISSUE TITLE
Allow inline arrays

### ISSUE THREAD

**Issue by chky-nmnsoftware** [AnyRoad/react-json-view-lite#51]
Just like the title says, I believe it would be very useful to have the ability to make arrays display as inline arrays. This could be configurable. This would most likely disable the expanding functionality. This could be configurable to be enabled on shallow arrays with primitives.

**Comment by fabiradi** [comment]
I use custom styles, that can optionally collapse "short" arrays (max. 5 items) and objects into one line **just via CSS**. This might be an interesting option to consider.

This is part of the code (CSS modules):
```css
  &.compactObject .basicChildStyle > .childFieldsContainer:not(:has(:nth-child(5))) {
    display: inline;
    padding-left: 0;
    border-left: none;

    & > .basicChildStyle {
      display: inline-block;

      &:last-child {
        margin-right: 0.15em;
      }
    }
  }
```

The rendering works quite well for me showing small array and objects in a more compact way. It definitely not really finished and has its issues with the "detection" of small objects (just counting the props), but it's a lot better for many occasions that just showing everything below each other.

> The collapsing does not have a lot of effect anymore, but its left visible for now.

| regular  | compact | compact + collapsed |
| ------------- | ------------- | ------------- |
| <img width="186" height="397" alt="Image" src="https://github.com/user-attachments/assets/f20443ce-6fb5-411d-bbe1-e28e1162bbf2" />  | <img width="331" height="88" alt="Image" src="https://github.com/user-attachments/assets/b0a98e48-1a50-435f-87e8-7704de628514" />  |  <img width="161" height="85" alt="Image" src="https://github.com/user-attachments/assets/3e0de273-3139-458e-bca0-7782a68d7bd1" /> |
